/**
 * Shopping-list entities. Port of `domain/entities/shopping.py`.
 *
 * A shopping list is generated by aggregating the ingredients of every recipe
 * scheduled in a week (see ShoppingAggregator). It is persisted (not recomputed
 * on read) because check-off state lives on it.
 */
import type { Decimal } from "decimal.js";

import type { Id } from "../identity";

export interface ShoppingListItem {
  ingredientName: string;
  unit?: string | null;
  totalQuantity?: Decimal | null;
  checked?: boolean;
  /** Grocery-aisle category (see services/ingredient-categories.ts); null → "Other". */
  category?: string | null;
  ingredientId?: Id | null;
  sourceEventIds?: Id[];
  id?: Id | null;
}

export interface ShoppingList {
  name: string;
  weekStart: string;
  weekEnd: string;
  items?: ShoppingListItem[];
  id?: Id | null;
  generatedAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}
