/**
 * Shopping-list entities. Port of `domain/entities/shopping.py`.
 *
 * A shopping list is generated by aggregating the ingredients of every recipe
 * scheduled in a week (see ShoppingAggregator). It is persisted (not recomputed
 * on read) because check-off state and export ids live on it.
 */
import type { Decimal } from "decimal.js";

export enum ShoppingListStatus {
  DRAFT = "draft",
  EXPORTED = "exported",
}

export interface ShoppingListItem {
  ingredientName: string;
  unit?: string | null;
  totalQuantity?: Decimal | null;
  checked?: boolean;
  ingredientId?: number | null;
  externalTaskId?: string | null;
  sourceEventIds?: number[];
  id?: number | null;
}

export interface ShoppingList {
  name: string;
  weekStart: string;
  weekEnd: string;
  status?: ShoppingListStatus;
  items?: ShoppingListItem[];
  id?: number | null;
  /** External task-list id (e.g. Google Tasks) for idempotent re-export. */
  externalTasklistId?: string | null;
  generatedAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}
