/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipes */
        get: operations["list_recipes_recipes_get"];
        put?: never;
        /** Create Recipe */
        post: operations["create_recipe_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_recipes__recipe_id__get"];
        /** Update Recipe */
        put: operations["update_recipe_recipes__recipe_id__put"];
        post?: never;
        /** Delete Recipe */
        delete: operations["delete_recipe_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{recipe_id}/macros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recipe Macros */
        get: operations["recipe_macros_recipes__recipe_id__macros_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{recipe_id}/ingredients/{position}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Ingredient */
        post: operations["link_ingredient_recipes__recipe_id__ingredients__position__link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foods/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Foods */
        get: operations["search_foods_foods_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestion Jobs */
        get: operations["list_ingestion_jobs_ingestion_jobs_get"];
        put?: never;
        /** Create Ingestion Job */
        post: operations["create_ingestion_job_ingestion_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/jobs/from-html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Ingestion Job From Html
         * @description Import a recipe from HTML captured by the in-app browser.
         *
         *     Used for bot-protected pages (e.g. Cloudflare JS challenges) that a
         *     server-side fetch can't get past: the in-app WebView renders the page as a
         *     real browser, then the captured HTML is parsed here with no network fetch.
         *     Always treated as a web page (videos use the URL path).
         */
        post: operations["create_ingestion_job_from_html_ingestion_jobs_from_html_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Job */
        get: operations["get_ingestion_job_ingestion_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Week Plan */
        get: operations["week_plan_meals_get"];
        put?: never;
        /** Schedule Meal */
        post: operations["schedule_meal_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meal */
        get: operations["get_meal_meals__event_id__get"];
        /** Update Meal */
        put: operations["update_meal_meals__event_id__put"];
        post?: never;
        /** Delete Meal */
        delete: operations["delete_meal_meals__event_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shopping Lists */
        get: operations["list_shopping_lists_shopping_lists_get"];
        put?: never;
        /** Generate Shopping List */
        post: operations["generate_shopping_list_shopping_lists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-lists/{list_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shopping List */
        get: operations["get_shopping_list_shopping_lists__list_id__get"];
        put?: never;
        post?: never;
        /** Delete Shopping List */
        delete: operations["delete_shopping_list_shopping_lists__list_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-lists/{list_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Shopping List */
        post: operations["export_shopping_list_shopping_lists__list_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-lists/{list_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle Item */
        patch: operations["toggle_item_shopping_lists__list_id__items__item_id__patch"];
        trace?: never;
    };
    "/integrations/google-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Tasks Status */
        get: operations["google_tasks_status_integrations_google_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/google-tasks/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Tasks Connect */
        post: operations["google_tasks_connect_integrations_google_tasks_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings Status */
        get: operations["get_settings_status_settings_get"];
        /** Update Settings */
        put: operations["update_settings_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DayMacrosOut */
        DayMacrosOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Totals */
            totals: {
                [key: string]: string;
            };
        };
        /** FoodSummaryOut */
        FoodSummaryOut: {
            /** Fdc Id */
            fdc_id: number;
            /** Description */
            description: string;
            /** Data Type */
            data_type?: string | null;
        };
        /** GenerateShoppingListRequest */
        GenerateShoppingListRequest: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /**
             * Week End
             * Format: date
             */
            week_end: string;
            /** Name */
            name?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionInputType
         * @description How the source should be fetched: a web page (scraper) or a video (captions).
         * @enum {string}
         */
        IngestionInputType: "web" | "video";
        /** IngestionJobCreate */
        IngestionJobCreate: {
            /**
             * Url
             * @description Recipe page or video URL to import.
             */
            url: string;
            /** @description Force 'web' or 'video' handling; auto-detected from the URL when omitted. */
            input_type?: components["schemas"]["IngestionInputType"] | null;
        };
        /**
         * IngestionJobFromHtml
         * @description Import from page HTML captured by the in-app browser (no server fetch).
         */
        IngestionJobFromHtml: {
            /**
             * Url
             * @description The page's URL, used as the recipe source.
             */
            url: string;
            /**
             * Html
             * @description Rendered page HTML captured by the in-app WebView.
             */
            html: string;
        };
        /** IngestionJobOut */
        IngestionJobOut: {
            /** Id */
            id: number;
            /** Input Url */
            input_url: string;
            input_type: components["schemas"]["IngestionInputType"];
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /** Result Recipe Id */
            result_recipe_id: number | null;
            /** Error */
            error: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** IngredientLineIn */
        IngredientLineIn: {
            /** Name */
            name: string;
            /** Quantity */
            quantity?: number | string | null;
            /** Unit */
            unit?: string | null;
            /** Raw Text */
            raw_text?: string | null;
            /** Notes */
            notes?: string | null;
            /** Usda Fdc Id */
            usda_fdc_id?: number | null;
            /** Gram Weight */
            gram_weight?: number | string | null;
        };
        /** IngredientLineOut */
        IngredientLineOut: {
            /** Id */
            id?: number | null;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Name */
            name: string;
            /** Quantity */
            quantity?: string | null;
            /** Unit */
            unit?: string | null;
            /** Raw Text */
            raw_text?: string | null;
            /** Notes */
            notes?: string | null;
            /** Usda Fdc Id */
            usda_fdc_id?: number | null;
            /** Gram Weight */
            gram_weight?: string | null;
        };
        /** IntegrationStatusOut */
        IntegrationStatusOut: {
            /** Provider */
            provider: string;
            /** Connected */
            connected: boolean;
            /** Client Configured */
            client_configured: boolean;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /** LineMacroOut */
        LineMacroOut: {
            /** Recipe Ingredient Id */
            recipe_ingredient_id: number | null;
            /** Ingredient Name */
            ingredient_name: string;
            /** Fdc Id */
            fdc_id: number | null;
            /** Gram Weight */
            gram_weight: string | null;
            /** Resolved */
            resolved: boolean;
            /** Macros */
            macros: {
                [key: string]: string;
            };
        };
        /** LinkIngredientRequest */
        LinkIngredientRequest: {
            /** Fdc Id */
            fdc_id: number;
            /** Gram Weight */
            gram_weight: number | string;
        };
        /**
         * MacroBreakdownOut
         * @description Recipe totals + the per-ingredient breakdown (the diagnostics view).
         */
        MacroBreakdownOut: {
            /** Totals */
            totals: {
                [key: string]: string;
            };
            /** Per Serving */
            per_serving: {
                [key: string]: string;
            } | null;
            /** Unresolved Count */
            unresolved_count: number;
            /** Lines */
            lines: components["schemas"]["LineMacroOut"][];
        };
        /** MealEventCreate */
        MealEventCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            meal_type: components["schemas"]["MealType"];
            /** Recipe Id */
            recipe_id: number;
            /**
             * Servings Planned
             * @default 1
             */
            servings_planned: number | string;
            /** Notes */
            notes?: string | null;
        };
        /** MealEventOut */
        MealEventOut: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            meal_type: components["schemas"]["MealType"];
            /** Recipe Id */
            recipe_id: number;
            /** Recipe Title */
            recipe_title: string | null;
            /** Servings Planned */
            servings_planned: string;
            /** Notes */
            notes: string | null;
        };
        /**
         * MealType
         * @enum {string}
         */
        MealType: "breakfast" | "lunch" | "dinner" | "snack";
        /** RecipeCreate */
        RecipeCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** @default manual */
            source_type: components["schemas"]["SourceType"];
            /** Servings */
            servings?: number | null;
            /** Rating */
            rating?: number | null;
            /** @default draft */
            status: components["schemas"]["RecipeStatus"];
            /** Instructions Md */
            instructions_md?: string | null;
            /** Calories Per Serving */
            calories_per_serving?: number | string | null;
            /** Protein Per Serving */
            protein_per_serving?: number | string | null;
            /** Fat Per Serving */
            fat_per_serving?: number | string | null;
            /** Carbs Per Serving */
            carbs_per_serving?: number | string | null;
            /** Fiber Per Serving */
            fiber_per_serving?: number | string | null;
            /** Sodium Per Serving */
            sodium_per_serving?: number | string | null;
            /** Ingredients */
            ingredients?: components["schemas"]["IngredientLineIn"][];
            /** Tags */
            tags?: string[];
        };
        /** RecipeOut */
        RecipeOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Source Url */
            source_url: string | null;
            source_type: components["schemas"]["SourceType"];
            /** Servings */
            servings: number | null;
            /** Rating */
            rating: number | null;
            status: components["schemas"]["RecipeStatus"];
            /** Instructions Md */
            instructions_md: string | null;
            /** Calories Per Serving */
            calories_per_serving: string | null;
            /** Protein Per Serving */
            protein_per_serving: string | null;
            /** Fat Per Serving */
            fat_per_serving: string | null;
            /** Carbs Per Serving */
            carbs_per_serving: string | null;
            /** Fiber Per Serving */
            fiber_per_serving: string | null;
            /** Sodium Per Serving */
            sodium_per_serving: string | null;
            /** Ingredients */
            ingredients: components["schemas"]["IngredientLineOut"][];
            /** Tags */
            tags: components["schemas"]["TagOut"][];
        };
        /**
         * RecipeStatus
         * @enum {string}
         */
        RecipeStatus: "draft" | "finalized";
        /** RecipeSummary */
        RecipeSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            status: components["schemas"]["RecipeStatus"];
            /** Rating */
            rating: number | null;
            /** Servings */
            servings: number | null;
            /** Tags */
            tags: string[];
        };
        /** SecretStatus */
        SecretStatus: {
            /** Configured */
            configured: boolean;
            /** Hint */
            hint?: string | null;
        };
        /** SettingsStatusOut */
        SettingsStatusOut: {
            fdc_api_key: components["schemas"]["SecretStatus"];
            anthropic_api_key: components["schemas"]["SecretStatus"];
            /** Anthropic Model */
            anthropic_model: string;
        };
        /**
         * SettingsUpdateIn
         * @description A partial update. Per-field semantics rely on which keys are *present*:
         *     a field omitted from the body is left unchanged; sent as an empty string it
         *     is cleared; sent with a value it is set. (The router inspects
         *     ``model_fields_set`` to tell "omitted" from "explicitly cleared".)
         */
        SettingsUpdateIn: {
            /** Fdc Api Key */
            fdc_api_key?: string | null;
            /** Anthropic Api Key */
            anthropic_api_key?: string | null;
            /** Anthropic Model */
            anthropic_model?: string | null;
        };
        /** ShoppingItemOut */
        ShoppingItemOut: {
            /** Id */
            id: number;
            /** Ingredient Id */
            ingredient_id: number | null;
            /** Ingredient Name */
            ingredient_name: string;
            /** Unit */
            unit: string | null;
            /** Total Quantity */
            total_quantity: string | null;
            /** Checked */
            checked: boolean;
            /** Source Event Ids */
            source_event_ids: number[];
            /** External Task Id */
            external_task_id: string | null;
        };
        /** ShoppingListOut */
        ShoppingListOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /**
             * Week End
             * Format: date
             */
            week_end: string;
            status: components["schemas"]["ShoppingListStatus"];
            /** Generated At */
            generated_at: string | null;
            /** External Tasklist Id */
            external_tasklist_id: string | null;
            /** Items */
            items: components["schemas"]["ShoppingItemOut"][];
        };
        /**
         * ShoppingListStatus
         * @enum {string}
         */
        ShoppingListStatus: "draft" | "exported";
        /**
         * ShoppingListSummary
         * @description Lightweight list-view row: counts instead of the full item set.
         */
        ShoppingListSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /**
             * Week End
             * Format: date
             */
            week_end: string;
            status: components["schemas"]["ShoppingListStatus"];
            /** Generated At */
            generated_at: string | null;
            /** Item Count */
            item_count: number;
            /** Checked Count */
            checked_count: number;
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "web" | "video" | "manual";
        /** TagOut */
        TagOut: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
        };
        /** ToggleItemRequest */
        ToggleItemRequest: {
            /** Checked */
            checked: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeekMacrosOut */
        WeekMacrosOut: {
            /** Days */
            days: components["schemas"]["DayMacrosOut"][];
            /** Totals */
            totals: {
                [key: string]: string;
            };
        };
        /**
         * WeekPlanOut
         * @description Everything the calendar needs for a date range in one response:
         *     the scheduled events plus the per-day and whole-range macro rollups.
         */
        WeekPlanOut: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Events */
            events: components["schemas"]["MealEventOut"][];
            macros: components["schemas"]["WeekMacrosOut"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_recipes_recipes_get: {
        parameters: {
            query?: {
                tag?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recipe_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recipe_recipes__recipe_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipe_recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    recipe_macros_recipes__recipe_id__macros_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroBreakdownOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_ingredient_recipes__recipe_id__ingredients__position__link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
                position: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkIngredientRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_foods_foods_search_get: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestion_jobs_ingestion_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobOut"][];
                };
            };
        };
    };
    create_ingestion_job_ingestion_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ingestion_job_from_html_ingestion_jobs_from_html_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionJobFromHtml"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_job_ingestion_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_plan_meals_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_meal_meals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealEventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meal_meals__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealEventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_meals__event_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealEventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_meals__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shopping_lists_shopping_lists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListSummary"][];
                };
            };
        };
    };
    generate_shopping_list_shopping_lists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateShoppingListRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shopping_list_shopping_lists__list_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shopping_list_shopping_lists__list_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_shopping_list_shopping_lists__list_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_item_shopping_lists__list_id__items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: number;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_tasks_status_integrations_google_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusOut"];
                };
            };
        };
    };
    google_tasks_connect_integrations_google_tasks_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusOut"];
                };
            };
        };
    };
    get_settings_status_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsStatusOut"];
                };
            };
        };
    };
    update_settings_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
