/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipes */
        get: operations["list_recipes_recipes_get"];
        put?: never;
        /** Create Recipe */
        post: operations["create_recipe_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_recipes__recipe_id__get"];
        /** Update Recipe */
        put: operations["update_recipe_recipes__recipe_id__put"];
        post?: never;
        /** Delete Recipe */
        delete: operations["delete_recipe_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{recipe_id}/macros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recipe Macros */
        get: operations["recipe_macros_recipes__recipe_id__macros_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{recipe_id}/ingredients/{position}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Ingredient */
        post: operations["link_ingredient_recipes__recipe_id__ingredients__position__link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foods/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Foods */
        get: operations["search_foods_foods_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FoodSummaryOut */
        FoodSummaryOut: {
            /** Fdc Id */
            fdc_id: number;
            /** Description */
            description: string;
            /** Data Type */
            data_type?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngredientLineIn */
        IngredientLineIn: {
            /** Name */
            name: string;
            /** Quantity */
            quantity?: number | string | null;
            /** Unit */
            unit?: string | null;
            /** Raw Text */
            raw_text?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** IngredientLineOut */
        IngredientLineOut: {
            /** Id */
            id?: number | null;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Name */
            name: string;
            /** Quantity */
            quantity?: string | null;
            /** Unit */
            unit?: string | null;
            /** Raw Text */
            raw_text?: string | null;
            /** Notes */
            notes?: string | null;
            /** Usda Fdc Id */
            usda_fdc_id?: number | null;
            /** Gram Weight */
            gram_weight?: string | null;
        };
        /** LineMacroOut */
        LineMacroOut: {
            /** Recipe Ingredient Id */
            recipe_ingredient_id: number | null;
            /** Ingredient Name */
            ingredient_name: string;
            /** Fdc Id */
            fdc_id: number | null;
            /** Gram Weight */
            gram_weight: string | null;
            /** Resolved */
            resolved: boolean;
            /** Macros */
            macros: {
                [key: string]: string;
            };
        };
        /** LinkIngredientRequest */
        LinkIngredientRequest: {
            /** Fdc Id */
            fdc_id: number;
            /** Gram Weight */
            gram_weight: number | string;
        };
        /**
         * MacroBreakdownOut
         * @description Recipe totals + the per-ingredient breakdown (the diagnostics view).
         */
        MacroBreakdownOut: {
            /** Totals */
            totals: {
                [key: string]: string;
            };
            /** Per Serving */
            per_serving: {
                [key: string]: string;
            } | null;
            /** Unresolved Count */
            unresolved_count: number;
            /** Lines */
            lines: components["schemas"]["LineMacroOut"][];
        };
        /** RecipeCreate */
        RecipeCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** @default manual */
            source_type: components["schemas"]["SourceType"];
            /** Servings */
            servings?: number | null;
            /** Rating */
            rating?: number | null;
            /** @default draft */
            status: components["schemas"]["RecipeStatus"];
            /** Instructions Md */
            instructions_md?: string | null;
            /** Ingredients */
            ingredients?: components["schemas"]["IngredientLineIn"][];
            /** Tags */
            tags?: string[];
        };
        /** RecipeOut */
        RecipeOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Source Url */
            source_url: string | null;
            source_type: components["schemas"]["SourceType"];
            /** Servings */
            servings: number | null;
            /** Rating */
            rating: number | null;
            status: components["schemas"]["RecipeStatus"];
            /** Instructions Md */
            instructions_md: string | null;
            /** Ingredients */
            ingredients: components["schemas"]["IngredientLineOut"][];
            /** Tags */
            tags: components["schemas"]["TagOut"][];
        };
        /**
         * RecipeStatus
         * @enum {string}
         */
        RecipeStatus: "draft" | "finalized";
        /** RecipeSummary */
        RecipeSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            status: components["schemas"]["RecipeStatus"];
            /** Rating */
            rating: number | null;
            /** Servings */
            servings: number | null;
            /** Tags */
            tags: string[];
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "web" | "video" | "manual";
        /** TagOut */
        TagOut: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_recipes_recipes_get: {
        parameters: {
            query?: {
                tag?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recipe_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recipe_recipes__recipe_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipe_recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    recipe_macros_recipes__recipe_id__macros_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroBreakdownOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_ingredient_recipes__recipe_id__ingredients__position__link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
                position: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkIngredientRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_foods_foods_search_get: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
