"""Shopping-list domain entities — pure, framework-free.

A shopping list is generated by aggregating the ingredients of every recipe
scheduled in a week (see ShoppingAggregator). It is persisted (not recomputed on
read) because check-off state and Google Tasks export ids (Phase 6) live on it.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date as Date
from datetime import datetime
from decimal import Decimal
from enum import Enum


class ShoppingListStatus(str, Enum):
    DRAFT = "draft"
    EXPORTED = "exported"


@dataclass
class ShoppingListItem:
    """One aggregated grocery line: an ingredient + unit with the summed quantity
    needed across the week. `source_event_ids` records which meal events drove it;
    `external_task_id` is reserved for idempotent Google Tasks sync (Phase 6)."""

    ingredient_name: str
    unit: str | None = None
    total_quantity: Decimal | None = None
    checked: bool = False
    ingredient_id: int | None = None
    external_task_id: str | None = None
    source_event_ids: list[int] = field(default_factory=list)
    id: int | None = None


@dataclass
class ShoppingList:
    name: str
    week_start: Date
    week_end: Date
    status: ShoppingListStatus = ShoppingListStatus.DRAFT
    items: list[ShoppingListItem] = field(default_factory=list)
    id: int | None = None
    generated_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
