"""phase2 usda nutrition cache

Revision ID: 4a42f0e9e0ee
Revises: 98f0cf741308
Create Date: 2026-06-02 18:11:27.311212
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a42f0e9e0ee'
down_revision: Union[str, None] = '98f0cf741308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usda_nutrient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usda_nutrient_id')
    )
    op.create_table('usda_foods',
    sa.Column('fdc_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fdc_id')
    )
    with op.batch_alter_table('usda_foods', schema=None) as batch_op:
        batch_op.create_index('ix_usda_foods_description', ['description'], unique=False)

    op.create_table('usda_food_nutrients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fdc_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_name', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fdc_id'], ['usda_foods.fdc_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usda_food_nutrients', schema=None) as batch_op:
        batch_op.create_index('ix_usda_food_nutrients_fdc_nutrient', ['fdc_id', 'nutrient_id'], unique=True)

    op.create_table('usda_food_portions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fdc_id', sa.Integer(), nullable=False),
    sa.Column('portion_description', sa.String(length=256), nullable=True),
    sa.Column('gram_weight', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fdc_id'], ['usda_foods.fdc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usda_food_portions')
    with op.batch_alter_table('usda_food_nutrients', schema=None) as batch_op:
        batch_op.drop_index('ix_usda_food_nutrients_fdc_nutrient')

    op.drop_table('usda_food_nutrients')
    with op.batch_alter_table('usda_foods', schema=None) as batch_op:
        batch_op.drop_index('ix_usda_foods_description')

    op.drop_table('usda_foods')
    op.drop_table('nutrients')
    # ### end Alembic commands ###
